In [62]:
import numpy as np
import pandas as pd
import keras

# Importing Data

In [63]:
BBB_Train = pd.read_csv("BBB_LSTM_Input_Train.csv")
DDD_Train = pd.read_csv("DDD_LSTM_Input_Train.csv")
FFF_Train = pd.read_csv("FFF_LSTM_Input_Train.csv")

BBB_Test = pd.read_csv("BBB_LSTM_Input_Test.csv")
DDD_Test = pd.read_csv("DDD_LSTM_Input_Test.csv")
FFF_Test = pd.read_csv("FFF_LSTM_Input_Test.csv")

BBB_AUX_Train = pd.read_csv("BBB_LSTM_AUX_Train.csv", index_col=0)
DDD_AUX_Train = pd.read_csv("DDD_LSTM_AUX_Train.csv", index_col=0)
FFF_AUX_Train = pd.read_csv("FFF_LSTM_AUX_Train.csv", index_col=0)

BBB_AUX_Test = pd.read_csv("BBB_LSTM_AUX_Test.csv", index_col=0)
DDD_AUX_Test = pd.read_csv("DDD_LSTM_AUX_Test.csv", index_col=0)
FFF_AUX_Test = pd.read_csv("FFF_LSTM_AUX_Test.csv", index_col=0)

# Transforming Data

In [64]:
BBB_Train_df = BBB_Train.iloc[:,3:6]
DDD_Train_df = DDD_Train.iloc[:,3:6]
FFF_Train_df = FFF_Train.iloc[:,3:6]

BBB_Test_df = BBB_Test.iloc[:,3:6]
DDD_Test_df = DDD_Test.iloc[:,3:6]
FFF_Test_df = FFF_Test.iloc[:,3:6]

In [65]:
BBB_Train_Targets = BBB_Train["final_result"][0::11]
DDD_Train_Targets = DDD_Train["final_result"][0::11]
FFF_Train_Targets = FFF_Train["final_result"][0::11]

BBB_Test_Targets = BBB_Test["final_result"][0::11]
DDD_Test_Targets = DDD_Test["final_result"][0::11]
FFF_Test_Targets = FFF_Test["final_result"][0::11]

In [66]:
FFF_Train_Targets.head(n=20)

0             Fail
11            Pass
22            Fail
33     Distinction
44            Pass
55            Pass
66            Fail
77            Pass
88            Fail
99            Pass
110           Pass
121           Pass
132           Pass
143           Pass
154           Pass
165           Pass
176           Pass
187           Fail
198           Fail
209           Pass
Name: final_result, dtype: object

In [67]:
FFF_Train_df.head(n=20)

Avg_Clicks  Asgmts  Avg_Asgmt_Score
0     2.159091       0         0.000000
1    23.260870       1        70.000000
2     0.708333       0        70.000000
3     0.708333       0        70.000000
4     6.958333       0        70.000000
5     1.208333       1        49.000000
6     0.000000       0        49.000000
7     0.000000       0        49.000000
8     0.000000       0        49.000000
9     0.000000       0        49.000000
10    0.000000       0        49.000000
11    6.196262       0         0.000000
12   34.086957       1        88.000000
13   22.625000       2        88.666667
14   20.208333       1        88.000000
15   29.416667       2        88.666667
16   19.583333       0        88.666667
17   26.708333       2        87.875000
18   12.791667       0        87.875000
19   13.666667       2        87.800000

#### Number of students in the courses across all 4 semesters

In [68]:
print("BBB Train\n")
print(BBB_Train_df.count()/11,"\n")

print("DDD Train\n")
print(DDD_Train_df.count()/11,"\n")

print("FFF Train\n")
print(FFF_Train_df.count()/11,"\n")

print("BBB Test\n")
print(BBB_Test_df.count()/11,"\n")

print("DDD Test\n")
print(DDD_Test_df.count()/11,"\n")

print("FFF Test\n")
print(FFF_Test_df.count()/11,"\n")

BBB Train

Avg_Clicks         3978.0
Asgmts             3978.0
Avg_Asgmt_Score    3978.0
dtype: float64 

DDD Train

Avg_Clicks         2866.0
Asgmts             2866.0
Avg_Asgmt_Score    2866.0
dtype: float64 

FFF Train

Avg_Clicks         3849.0
Asgmts             3849.0
Avg_Asgmt_Score    3849.0
dtype: float64 

BBB Test

Avg_Clicks         1543.0
Asgmts             1543.0
Avg_Asgmt_Score    1543.0
dtype: float64 

DDD Test

Avg_Clicks         1156.0
Asgmts             1156.0
Avg_Asgmt_Score    1156.0
dtype: float64 

FFF Test

Avg_Clicks         1510.0
Asgmts             1510.0
Avg_Asgmt_Score    1510.0
dtype: float64 



#### Convert dataframes into 2D arrays

In [69]:
BBB_Train_2D = BBB_Train_df.values
DDD_Train_2D = DDD_Train_df.values
FFF_Train_2D = FFF_Train_df.values

BBB_Test_2D = BBB_Test_df.values
DDD_Test_2D = DDD_Test_df.values
FFF_Test_2D = FFF_Test_df.values

#### Reshape 2D arrays to 3D arrays
Format : samples (students), timesteps (deciles), features (clicks & assignments)

In [70]:
BBB_Train_3D = BBB_Train_2D.reshape(int(BBB_Train_df["Avg_Clicks"].count()/11),11,len(BBB_Train_df.columns))
DDD_Train_3D = DDD_Train_2D.reshape(int(DDD_Train_df["Avg_Clicks"].count()/11),11,len(DDD_Train_df.columns))
FFF_Train_3D = FFF_Train_2D.reshape(int(FFF_Train_df["Avg_Clicks"].count()/11),11,len(FFF_Train_df.columns))

BBB_Test_3D = BBB_Test_2D.reshape(int(BBB_Test_df["Avg_Clicks"].count()/11),11,len(BBB_Test_df.columns))
DDD_Test_3D = DDD_Test_2D.reshape(int(DDD_Test_df["Avg_Clicks"].count()/11),11,len(DDD_Test_df.columns))
FFF_Test_3D = FFF_Test_2D.reshape(int(FFF_Test_df["Avg_Clicks"].count()/11),11,len(FFF_Test_df.columns))


In [71]:
FFF_Train_3D

array([[[  2.15909091e+00,   0.00000000e+00,   0.00000000e+00],
        [  2.32608696e+01,   1.00000000e+00,   7.00000000e+01],
        [  7.08333333e-01,   0.00000000e+00,   7.00000000e+01],
        [  7.08333333e-01,   0.00000000e+00,   7.00000000e+01],
        [  6.95833333e+00,   0.00000000e+00,   7.00000000e+01],
        [  1.20833333e+00,   1.00000000e+00,   4.90000000e+01],
        [  0.00000000e+00,   0.00000000e+00,   4.90000000e+01],
        [  0.00000000e+00,   0.00000000e+00,   4.90000000e+01],
        [  0.00000000e+00,   0.00000000e+00,   4.90000000e+01],
        [  0.00000000e+00,   0.00000000e+00,   4.90000000e+01],
        [  0.00000000e+00,   0.00000000e+00,   4.90000000e+01]],

       [[  6.19626168e+00,   0.00000000e+00,   0.00000000e+00],
        [  3.40869565e+01,   1.00000000e+00,   8.80000000e+01],
        [  2.26250000e+01,   2.00000000e+00,   8.86666667e+01],
        [  2.02083333e+01,   1.00000000e+00,   8.80000000e+01],
        [  2.94166667e+01,   2.0000000

In [72]:
print(FFF_Train_3D.shape)

(3849, 11, 3)


In [73]:
BBB_Train_Targets_1D = np.array(BBB_Train_Targets)
DDD_Train_Targets_1D = np.array(DDD_Train_Targets)
FFF_Train_Targets_1D = np.array(FFF_Train_Targets)

BBB_Test_Targets_1D = np.array(BBB_Test_Targets)
DDD_Test_Targets_1D = np.array(DDD_Test_Targets)
FFF_Test_Targets_1D = np.array(FFF_Test_Targets)


In [74]:
BBB_Train_Targets_1D[BBB_Train_Targets_1D == "Fail"] = 0
BBB_Train_Targets_1D[BBB_Train_Targets_1D == "Pass"] = 1
BBB_Train_Targets_1D[BBB_Train_Targets_1D == "Distinction"] = 1

DDD_Train_Targets_1D[DDD_Train_Targets_1D == "Fail"] = 0
DDD_Train_Targets_1D[DDD_Train_Targets_1D == "Pass"] = 1
DDD_Train_Targets_1D[DDD_Train_Targets_1D == "Distinction"] = 1

FFF_Train_Targets_1D[FFF_Train_Targets_1D == "Fail"] = 0
FFF_Train_Targets_1D[FFF_Train_Targets_1D == "Pass"] = 1
FFF_Train_Targets_1D[FFF_Train_Targets_1D == "Distinction"] = 1

BBB_Test_Targets_1D[BBB_Test_Targets_1D == "Fail"] = 0
BBB_Test_Targets_1D[BBB_Test_Targets_1D == "Pass"] = 1
BBB_Test_Targets_1D[BBB_Test_Targets_1D == "Distinction"] = 1

DDD_Test_Targets_1D[DDD_Test_Targets_1D == "Fail"] = 0
DDD_Test_Targets_1D[DDD_Test_Targets_1D == "Pass"] = 1
DDD_Test_Targets_1D[DDD_Test_Targets_1D == "Distinction"] = 1

FFF_Test_Targets_1D[FFF_Test_Targets_1D == "Fail"] = 0
FFF_Test_Targets_1D[FFF_Test_Targets_1D == "Pass"] = 1
FFF_Test_Targets_1D[FFF_Test_Targets_1D == "Distinction"] = 1

In [75]:
BBB_Train_Targets_1D = BBB_Train_Targets_1D.astype('int64')
DDD_Train_Targets_1D = DDD_Train_Targets_1D.astype('int64')
FFF_Train_Targets_1D = FFF_Train_Targets_1D.astype('int64')

BBB_Test_Targets_1D = BBB_Test_Targets_1D.astype('int64')
DDD_Test_Targets_1D = DDD_Test_Targets_1D.astype('int64')
FFF_Test_Targets_1D = FFF_Test_Targets_1D.astype('int64')

In [76]:
print(FFF_Train_Targets_1D.shape)

(3849,)


In [77]:
FFF_Train_Targets_1D

array([0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0,

# LSTM

In [78]:
from sklearn.metrics import classification_report
from keras import Sequential
from keras.layers import Input,Embedding, LSTM, Dense
from keras.models import Model
from keras.optimizers import SGD
np.random.seed(7)
np.set_printoptions(threshold=np.nan)

In [129]:
LSTM_input = Input(shape=(11,3), name='LSTM_input')
LSTM_out = LSTM(32)(LSTM_input)

auxiliary_input = Input(shape=(29,), name='aux_input')
auxiliary_layer = Dense(64, activation='relu')(auxiliary_input)
auxiliary_output = Dense(32, activation='relu')(auxiliary_layer)

x = keras.layers.concatenate([LSTM_out, auxiliary_output])


x = Dense(64, activation='relu')(x)
x = Dense(64, activation='relu')(x)
x = Dense(64, activation='relu')(x)

main_output = Dense(1, activation='sigmoid', name='main_output')(x)

model = Model(inputs=[LSTM_input, auxiliary_input], outputs=main_output)
model.compile(optimizer='rmsprop', loss='binary_crossentropy',metrics = ['accuracy'])

# LSTM Course BBB

### Train LSTM Course BBB

In [130]:
model.fit([BBB_Train_3D,BBB_AUX_Train], BBB_Train_Targets_1D, epochs=10, batch_size=1, verbose=1)

Epoch 1/10
3978/3978 [==============================] - 27s 7ms/step - loss: 0.4578 - acc: 0.8130
Epoch 2/10
3978/3978 [==============================] - 26s 7ms/step - loss: 0.3831 - acc: 0.8796
Epoch 3/10
3978/3978 [==============================] - 26s 7ms/step - loss: 0.3903 - acc: 0.8824
Epoch 4/10
3978/3978 [==============================] - 29s 7ms/step - loss: 0.4138 - acc: 0.8859
Epoch 5/10
3978/3978 [==============================] - 27s 7ms/step - loss: 0.4169 - acc: 0.8861
Epoch 6/10
3978/3978 [==============================] - 27s 7ms/step - loss: 0.4411 - acc: 0.8904
Epoch 7/10
3978/3978 [==============================] - 28s 7ms/step - loss: 0.4329 - acc: 0.8937
Epoch 8/10
3978/3978 [==============================] - 28s 7ms/step - loss: 0.4443 - acc: 0.8912
Epoch 9/10
3978/3978 [==============================] - 28s 7ms/step - loss: 0.5124 - acc: 0.8932
Epoch 10/10
3978/3978 [==============================] - 28s 7ms/step - loss: 0.4486 - acc: 0.8914


### Test LSTM Course BBB

In [131]:
y_pred_BBB = model.predict([BBB_Test_3D, BBB_AUX_Test])
y_classes_BBB = np.round(y_pred_BBB)
y_classes_BBB

array([[ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
      

In [132]:
print('Course BBB - 2 Target Classes')
print('Classification Report for LSTM predictions:')
print('-------------------------------------------')
print(classification_report(y_pred=y_classes_BBB, y_true=BBB_Test_Targets_1D))

Course BBB - 2 Target Classes
Classification Report for LSTM predictions:
-------------------------------------------
             precision    recall  f1-score   support

          0       0.64      0.89      0.74       391
          1       0.96      0.83      0.89      1152

avg / total       0.88      0.85      0.85      1543



# LSTM Course DDD

### Train LSTM Course DDD

In [100]:
model.fit([DDD_Train_3D,DDD_AUX_Train], DDD_Train_Targets_1D, epochs=10, batch_size=1, verbose=1)

Epoch 1/10
2866/2866 [==============================] - 19s 7ms/step - loss: 0.4515 - acc: 0.8109
Epoch 2/10
2866/2866 [==============================] - 19s 7ms/step - loss: 0.3181 - acc: 0.8901
Epoch 3/10
2866/2866 [==============================] - 17s 6ms/step - loss: 0.3061 - acc: 0.8988
Epoch 4/10
2866/2866 [==============================] - 16s 6ms/step - loss: 0.3021 - acc: 0.9023
Epoch 5/10
2866/2866 [==============================] - 16s 6ms/step - loss: 0.2979 - acc: 0.8974
Epoch 6/10
2866/2866 [==============================] - 15s 5ms/step - loss: 0.3069 - acc: 0.9009
Epoch 7/10
2866/2866 [==============================] - 15s 5ms/step - loss: 0.3619 - acc: 0.9040
Epoch 8/10
2866/2866 [==============================] - 15s 5ms/step - loss: 0.3133 - acc: 0.9096
Epoch 9/10
2866/2866 [==============================] - 15s 5ms/step - loss: 0.3046 - acc: 0.9082
Epoch 10/10
2866/2866 [==============================] - 16s 5ms/step - loss: 0.3283 - acc: 0.9093


Test LSTM Course DDD

In [133]:
y_pred_DDD = model.predict([DDD_Test_3D, DDD_AUX_Test])
y_classes_DDD = np.round(y_pred_DDD)
y_classes_DDD

array([[ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
      

In [134]:
print('Course DDD - 2 Target Classes')
print('Classification Report for LSTM predictions:')
print('-------------------------------------------')
print(classification_report(y_pred=y_classes_DDD, y_true=DDD_Test_Targets_1D))

Course DDD - 2 Target Classes
Classification Report for LSTM predictions:
-------------------------------------------
             precision    recall  f1-score   support

          0       0.97      0.59      0.73       364
          1       0.84      0.99      0.91       792

avg / total       0.88      0.86      0.85      1156



# LSTM Course FFF

### Train LSTM Course FFF

In [113]:
model.fit([FFF_Train_3D,FFF_AUX_Train], FFF_Train_Targets_1D, epochs=20, batch_size=32, verbose=1)

Epoch 1/20
3849/3849 [==============================] - 2s 569us/step - loss: 0.5421 - acc: 0.7454
Epoch 2/20
3849/3849 [==============================] - 1s 210us/step - loss: 0.2985 - acc: 0.8958
Epoch 3/20
3849/3849 [==============================] - 1s 214us/step - loss: 0.2371 - acc: 0.9111
Epoch 4/20
3849/3849 [==============================] - 1s 210us/step - loss: 0.2287 - acc: 0.9101
Epoch 5/20
3849/3849 [==============================] - 1s 212us/step - loss: 0.2136 - acc: 0.9163
Epoch 6/20
3849/3849 [==============================] - 1s 224us/step - loss: 0.2146 - acc: 0.9166
Epoch 7/20
3849/3849 [==============================] - 1s 215us/step - loss: 0.2134 - acc: 0.9187
Epoch 8/20
3849/3849 [==============================] - 1s 211us/step - loss: 0.2037 - acc: 0.9182
Epoch 9/20
3849/3849 [==============================] - 1s 212us/step - loss: 0.2091 - acc: 0.9202
Epoch 10/20
3849/3849 [==============================] - 1s 211us/step - loss: 0.1885 - acc: 0.9254
Epoch 11/

### Test LSTM Course FFF

In [114]:
y_pred_FFF = model.predict([FFF_Test_3D, FFF_AUX_Test])
y_classes_FFF = np.round(y_pred_FFF)
y_classes_FFF

array([[ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 0.],
       [ 0.],
       [ 1.],
       [ 0.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

In [115]:
print('Course FFF - 2 Target Classes')
print('Classification Report for LSTM predictions:')
print('-------------------------------------------')
print(classification_report(y_pred=y_classes_FFF, y_true=FFF_Test_Targets_1D))

Course FFF - 2 Target Classes
Classification Report for LSTM predictions:
-------------------------------------------
             precision    recall  f1-score   support

          0       0.92      0.81      0.87       393
          1       0.94      0.98      0.96      1117

avg / total       0.93      0.93      0.93      1510



Classification Report for LSTM predictions:
-------------------------------------------
             precision    recall  f1-score   support

          0       0.95      0.79      0.87       393
          1       0.93      0.99      0.96      1117

avg / total       0.94      0.94      0.93      1510



(1510,)