In [2]:
import numpy as np
import pandas as pd
import keras

# Importing Data

In [3]:
BBB_Train = pd.read_csv("BBB_LSTM_Input_Train.csv")
DDD_Train = pd.read_csv("DDD_LSTM_Input_Train.csv")
FFF_Train = pd.read_csv("FFF_LSTM_Input_Train.csv")

BBB_Test = pd.read_csv("BBB_LSTM_Input_Test.csv")
DDD_Test = pd.read_csv("DDD_LSTM_Input_Test.csv")
FFF_Test = pd.read_csv("FFF_LSTM_Input_Test.csv")

BBB_AUX_Train = pd.read_csv("BBB_LSTM_AUX_Train.csv", index_col=0)
DDD_AUX_Train = pd.read_csv("DDD_LSTM_AUX_Train.csv", index_col=0)
FFF_AUX_Train = pd.read_csv("FFF_LSTM_AUX_Train.csv", index_col=0)

BBB_AUX_Test = pd.read_csv("BBB_LSTM_AUX_Test.csv", index_col=0)
DDD_AUX_Test = pd.read_csv("DDD_LSTM_AUX_Test.csv", index_col=0)
FFF_AUX_Test = pd.read_csv("FFF_LSTM_AUX_Test.csv", index_col=0)


# Transforming Data

In [4]:
BBB_Train_df = BBB_Train.iloc[:,3:6]
DDD_Train_df = DDD_Train.iloc[:,3:6]
FFF_Train_df = FFF_Train.iloc[:,3:6]

BBB_Test_df = BBB_Test.iloc[:,3:6]
DDD_Test_df = DDD_Test.iloc[:,3:6]
FFF_Test_df = FFF_Test.iloc[:,3:6]

In [5]:
BBB_Train_Targets = BBB_Train["final_result"][0::11]
DDD_Train_Targets = DDD_Train["final_result"][0::11]
FFF_Train_Targets = FFF_Train["final_result"][0::11]

BBB_Test_Targets = BBB_Test["final_result"][0::11]
DDD_Test_Targets = DDD_Test["final_result"][0::11]
FFF_Test_Targets = FFF_Test["final_result"][0::11]

In [6]:
FFF_Train_Targets.head(n=20)

0             Fail
11            Pass
22            Fail
33     Distinction
44            Pass
55            Pass
66            Fail
77            Pass
88            Fail
99            Pass
110           Pass
121           Pass
132           Pass
143           Pass
154           Pass
165           Pass
176           Pass
187           Fail
198           Fail
209           Pass
Name: final_result, dtype: object

In [7]:
FFF_Train_df.head(n=20)

Avg_Clicks  Asgmts  Avg_Asgmt_Score
0     2.159091       0         0.000000
1    23.260870       1        70.000000
2     0.708333       0        70.000000
3     0.708333       0        70.000000
4     6.958333       0        70.000000
5     1.208333       1        49.000000
6     0.000000       0        49.000000
7     0.000000       0        49.000000
8     0.000000       0        49.000000
9     0.000000       0        49.000000
10    0.000000       0        49.000000
11    6.196262       0         0.000000
12   34.086957       1        88.000000
13   22.625000       2        88.666667
14   20.208333       1        88.000000
15   29.416667       2        88.666667
16   19.583333       0        88.666667
17   26.708333       2        87.875000
18   12.791667       0        87.875000
19   13.666667       2        87.800000

In [8]:
FFF_AUX_Train.head(n=20)

num_of_prev_attempts  studied_credits  gender_M  gender_F  \
1                      0              120         1         0   
2                      0               60         1         0   
3                      0               60         1         0   
4                      0               60         0         1   
5                      0               60         0         1   
6                      1               60         1         0   
7                      1              150         1         0   
8                      0               90         1         0   
9                      1              310         1         0   
10                     1              150         1         0   
11                     1               60         1         0   
12                     0               60         1         0   
13                     0               60         1         0   
14                     0               60         1         0   
15                     0               60         1         0   
16                     0               60         1         0   
17                     0               60         1         0   
18                     1              120         1         0   
19                     0               60         1         0   
20                     0               60         0         1   

    highest_education_A Level or Equivalent  \
1                                         1   
2                                         1   
3                                         0   
4                                         1   
5                                         0   
6                                         1   
7                                         1   
8                                         0   
9                                         0   
10                                        0   
11                                        0   
12                                        1   
13                                        0   
14                                        0   
15                                        0   
16                                        1   
17                                        1   
18                                        0   
19                                        1   
20                                        0   

    highest_education_Lower Than A Level  highest_education_HE Qualification  \
1                                      0                                   0   
2                                      0                                   0   
3                                      1                                   0   
4                                      0                                   0   
5                                      0                                   1   
6                                      0                                   0   
7                                      0                                   0   
8                                      0                                   1   
9                                      1                                   0   
10                                     0                                   1   
11                                     0                                   1   
12                                     0                                   0   
13                                     1                                   0   
14                                     1                                   0   
15                                     0                                   1   
16                                     0                                   0   
17                                     0                                   0   
18                                     0                                   1   
19                                     0                                   0   
20                                     1          

In [9]:
#BBB_AUX_Train = BBB_AUX_Train.drop(columns = ["num_of_prev_attempts", "gender_M", "gender_F", "disability_N", "disability_Y", "year_2013", "year_2014", "semester_B", "semester_J"])
#DDD_AUX_Train = DDD_AUX_Train.drop(columns = ["num_of_prev_attempts", "gender_M", "gender_F", "disability_N", "disability_Y", "year_2013", "year_2014", "semester_B", "semester_J"])
#FFF_AUX_Train = FFF_AUX_Train.drop(columns = ["num_of_prev_attempts", "gender_M", "gender_F", "disability_N", "disability_Y", "year_2013", "year_2014", "semester_B", "semester_J"])

#BBB_AUX_Test = BBB_AUX_Test.drop(columns = ["num_of_prev_attempts", "gender_M", "gender_F", "disability_N", "disability_Y", "year_2013", "year_2014", "semester_B", "semester_J"])
#DDD_AUX_Test = DDD_AUX_Test.drop(columns = ["num_of_prev_attempts", "gender_M", "gender_F", "disability_N", "disability_Y", "year_2013", "year_2014", "semester_B", "semester_J"])
#FFF_AUX_Test = FFF_AUX_Test.drop(columns = ["num_of_prev_attempts", "gender_M", "gender_F", "disability_N", "disability_Y", "year_2013", "year_2014", "semester_B", "semester_J"])

In [10]:
BBB_AUX_Train = np.array(BBB_AUX_Train)
DDD_AUX_Train = np.array(DDD_AUX_Train)
FFF_AUX_Train = np.array(FFF_AUX_Train)

BBB_AUX_Test = np.array(BBB_AUX_Test)
DDD_AUX_Test = np.array(DDD_AUX_Test)
FFF_AUX_Test = np.array(FFF_AUX_Test)

In [11]:
BBB_AUX_Train.shape

(3978, 29)

Number of students in the courses across all 4 semesters

In [12]:
print("BBB Train\n")
print(BBB_Train_df.count()/11,"\n")

print("DDD Train\n")
print(DDD_Train_df.count()/11,"\n")

print("FFF Train\n")
print(FFF_Train_df.count()/11,"\n")

print("BBB Test\n")
print(BBB_Test_df.count()/11,"\n")

print("DDD Test\n")
print(DDD_Test_df.count()/11,"\n")

print("FFF Test\n")
print(FFF_Test_df.count()/11,"\n")

BBB Train

Avg_Clicks         3978.0
Asgmts             3978.0
Avg_Asgmt_Score    3978.0
dtype: float64 

DDD Train

Avg_Clicks         2866.0
Asgmts             2866.0
Avg_Asgmt_Score    2866.0
dtype: float64 

FFF Train

Avg_Clicks         3849.0
Asgmts             3849.0
Avg_Asgmt_Score    3849.0
dtype: float64 

BBB Test

Avg_Clicks         1543.0
Asgmts             1543.0
Avg_Asgmt_Score    1543.0
dtype: float64 

DDD Test

Avg_Clicks         1156.0
Asgmts             1156.0
Avg_Asgmt_Score    1156.0
dtype: float64 

FFF Test

Avg_Clicks         1510.0
Asgmts             1510.0
Avg_Asgmt_Score    1510.0
dtype: float64 



Convert dataframes into 2D arrays

In [13]:
BBB_Train_2D = BBB_Train_df.values
DDD_Train_2D = DDD_Train_df.values
FFF_Train_2D = FFF_Train_df.values

BBB_Test_2D = BBB_Test_df.values
DDD_Test_2D = DDD_Test_df.values
FFF_Test_2D = FFF_Test_df.values

Reshape 2D arrays to 3D arrays
Format : samples (students), timesteps (deciles), features (clicks & assignments)

In [14]:
BBB_Train_3D = BBB_Train_2D.reshape(int(BBB_Train_df["Asgmts"].count()/11),11,len(BBB_Train_df.columns))
DDD_Train_3D = DDD_Train_2D.reshape(int(DDD_Train_df["Asgmts"].count()/11),11,len(DDD_Train_df.columns))
FFF_Train_3D = FFF_Train_2D.reshape(int(FFF_Train_df["Asgmts"].count()/11),11,len(FFF_Train_df.columns))

BBB_Test_3D = BBB_Test_2D.reshape(int(BBB_Test_df["Asgmts"].count()/11),11,len(BBB_Test_df.columns))
DDD_Test_3D = DDD_Test_2D.reshape(int(DDD_Test_df["Asgmts"].count()/11),11,len(DDD_Test_df.columns))
FFF_Test_3D = FFF_Test_2D.reshape(int(FFF_Test_df["Asgmts"].count()/11),11,len(FFF_Test_df.columns))


In [15]:
FFF_Train_3D

array([[[  2.15909091,   0.        ,   0.        ],
        [ 23.26086957,   1.        ,  70.        ],
        [  0.70833333,   0.        ,  70.        ],
        ..., 
        [  0.        ,   0.        ,  49.        ],
        [  0.        ,   0.        ,  49.        ],
        [  0.        ,   0.        ,  49.        ]],

       [[  6.19626168,   0.        ,   0.        ],
        [ 34.08695652,   1.        ,  88.        ],
        [ 22.625     ,   2.        ,  88.66666667],
        ..., 
        [ 13.66666667,   2.        ,  87.8       ],
        [ 15.875     ,   0.        ,  87.8       ],
        [ 38.45833333,   2.        ,  88.91666667]],

       [[  1.80952381,   0.        ,   0.        ],
        [ 16.2173913 ,   1.        ,  76.        ],
        [  8.66666667,   0.        ,  76.        ],
        ..., 
        [  0.        ,   0.        ,  69.        ],
        [  0.375     ,   0.        ,  69.        ],
        [  0.        ,   0.        ,  69.        ]],

       ..., 
   

In [16]:
print(FFF_Train_3D.shape)

(3849, 11, 3)


In [17]:
BBB_Train_Targets_1HE = np.array(pd.get_dummies(BBB_Train_Targets))
DDD_Train_Targets_1HE = np.array(pd.get_dummies(DDD_Train_Targets))
FFF_Train_Targets_1HE = np.array(pd.get_dummies(FFF_Train_Targets))

BBB_Test_Targets_1HE = np.array(pd.get_dummies(BBB_Test_Targets))
DDD_Test_Targets_1HE = np.array(pd.get_dummies(DDD_Test_Targets))
FFF_Test_Targets_1HE = np.array(pd.get_dummies(FFF_Test_Targets))


In [18]:
BBB_Train_Targets_1D = np.array(BBB_Train_Targets)
DDD_Train_Targets_1D = np.array(DDD_Train_Targets)
FFF_Train_Targets_1D = np.array(FFF_Train_Targets)

BBB_Test_Targets_1D = np.array(BBB_Test_Targets)
DDD_Test_Targets_1D = np.array(DDD_Test_Targets)
FFF_Test_Targets_1D = np.array(FFF_Test_Targets)

In [19]:
BBB_Train_Targets_1D[BBB_Train_Targets_1D == "Fail"] = 1
BBB_Train_Targets_1D[BBB_Train_Targets_1D == "Pass"] = 2
BBB_Train_Targets_1D[BBB_Train_Targets_1D == "Distinction"] = 0

DDD_Train_Targets_1D[DDD_Train_Targets_1D == "Fail"] = 1
DDD_Train_Targets_1D[DDD_Train_Targets_1D == "Pass"] = 2
DDD_Train_Targets_1D[DDD_Train_Targets_1D == "Distinction"] = 0

FFF_Train_Targets_1D[FFF_Train_Targets_1D == "Fail"] = 1
FFF_Train_Targets_1D[FFF_Train_Targets_1D == "Pass"] = 2
FFF_Train_Targets_1D[FFF_Train_Targets_1D == "Distinction"] = 0

BBB_Test_Targets_1D[BBB_Test_Targets_1D == "Fail"] = 1
BBB_Test_Targets_1D[BBB_Test_Targets_1D == "Pass"] = 2
BBB_Test_Targets_1D[BBB_Test_Targets_1D == "Distinction"] = 0

DDD_Test_Targets_1D[DDD_Test_Targets_1D == "Fail"] = 1
DDD_Test_Targets_1D[DDD_Test_Targets_1D == "Pass"] = 2
DDD_Test_Targets_1D[DDD_Test_Targets_1D == "Distinction"] = 0

FFF_Test_Targets_1D[FFF_Test_Targets_1D == "Fail"] = 1
FFF_Test_Targets_1D[FFF_Test_Targets_1D == "Pass"] = 2
FFF_Test_Targets_1D[FFF_Test_Targets_1D == "Distinction"] = 0

In [20]:
BBB_Train_Targets_1D = BBB_Train_Targets_1D.astype('int64')
DDD_Train_Targets_1D = DDD_Train_Targets_1D.astype('int64')
FFF_Train_Targets_1D = FFF_Train_Targets_1D.astype('int64')

BBB_Test_Targets_1D = BBB_Test_Targets_1D.astype('int64')
DDD_Test_Targets_1D = DDD_Test_Targets_1D.astype('int64')
FFF_Test_Targets_1D = FFF_Test_Targets_1D.astype('int64')

In [21]:
BBB_Train_Targets_1HE

array([[0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       ..., 
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1]], dtype=uint8)

In [22]:
print(FFF_Train_Targets_1D.shape)

(3849,)


In [23]:
FFF_Train_Targets_1D

array([1, 2, 1, ..., 2, 2, 1], dtype=int64)

# LSTM

In [24]:
from sklearn.metrics import classification_report
from keras import Sequential
from keras.layers import Input,Embedding, LSTM, Dense
from keras.models import Model
from keras.optimizers import SGD
np.random.seed(7)
#np.set_printoptions(threshold=np.nan)

In [27]:
LSTM_input = Input(shape=(11,3), name='LSTM_input')
LSTM_out = LSTM(32)(LSTM_input)

auxiliary_input = Input(shape=(29,), name='aux_input')
auxiliary_layer = Dense(64, activation='relu')(auxiliary_input)
auxiliary_output = Dense(32, activation='relu')(auxiliary_layer)

x = keras.layers.concatenate([LSTM_out, auxiliary_output])

x = Dense(64, activation='relu')(x)
x = Dense(64, activation='relu')(x)
x = Dense(64, activation='relu')(x)

main_output = Dense(3, activation='softmax', name='main_output')(x)

model = Model(inputs=[LSTM_input, auxiliary_input], outputs=main_output)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics = ['accuracy'])

In [103]:
#auxiliary_input = Input(shape=(29,), name='aux_input')
#auxiliary_layer = Dense(64, activation='relu')(auxiliary_input)
#auxiliary_output = Dense(32, activation='relu')(auxiliary_layer)

#main_output = Dense(3, activation='softmax', name='main_output')(auxiliary_output)

#model = Model(inputs=auxiliary_input, outputs=main_output)
#model.compile(optimizer='rmsprop', loss='categorical_crossentropy',metrics = ['accuracy'])

<tf.Tensor 'lstm_14/TensorArrayReadV3:0' shape=(?, 32) dtype=float32>

# LSTM Course BBB

### Train LSTM Course BBB

In [64]:
model.fit(x=[BBB_Train_3D,BBB_AUX_Train], y=BBB_Train_Targets_1HE, epochs=20, batch_size=32, verbose=1)

Epoch 1/20
3978/3978 [==============================] - 2s 519us/step - loss: 1.3343 - acc: 0.4837
Epoch 2/20
3978/3978 [==============================] - 1s 221us/step - loss: 0.9199 - acc: 0.5882
Epoch 3/20
3978/3978 [==============================] - 1s 211us/step - loss: 0.7821 - acc: 0.6518
Epoch 4/20
3978/3978 [==============================] - 1s 235us/step - loss: 0.6934 - acc: 0.6978
Epoch 5/20
3978/3978 [==============================] - 1s 225us/step - loss: 0.6469 - acc: 0.7270
Epoch 6/20
3978/3978 [==============================] - 1s 239us/step - loss: 0.6096 - acc: 0.7443
Epoch 7/20
3978/3978 [==============================] - 1s 232us/step - loss: 0.6032 - acc: 0.7401
Epoch 8/20
3978/3978 [==============================] - 1s 222us/step - loss: 0.5798 - acc: 0.7481
Epoch 9/20
3978/3978 [==============================] - 1s 214us/step - loss: 0.5711 - acc: 0.7539
Epoch 10/20
3978/3978 [==============================] - 1s 202us/step - loss: 0.5549 - acc: 0.7624
Epoch 11/

### Test LSTM Course BBB

In [65]:
y_pred_BBB = model.predict([BBB_Test_3D, BBB_AUX_Test])
y_classes_BBB = np.argmax(y_pred_BBB,axis=1)
y_classes_BBB

array([2, 1, 2, 1, 1, 2, 2, 2, 0, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2,
       1, 0, 1, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2,
       0, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 0,
       2, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 0, 2,
       2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 2, 0, 2, 1, 2,
       1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 2,
       2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 0, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1,
       0, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 2,
       1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1,
       2, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1,
       1, 2, 1, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2,
       2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1,
       1, 2,

In [66]:
print('Course BBB - 3 Target Classes')
print('Classification Report for LSTM predictions:')
print('-------------------------------------------')
print(classification_report(y_pred=y_classes_BBB, y_true=BBB_Test_Targets_1D))


Course BBB - 3 Target Classes
Classification Report for LSTM predictions:
-------------------------------------------
             precision    recall  f1-score   support

          0       0.63      0.13      0.22       180
          1       0.47      0.87      0.61       391
          2       0.75      0.60      0.67       972

avg / total       0.67      0.62      0.60      1543



# LSTM COURSE DDD

### Train LSTM Course DDD

In [67]:
model.fit([DDD_Train_3D,DDD_AUX_Train], DDD_Train_Targets_1HE, epochs=20, batch_size=32, verbose=1)

Epoch 1/20
2866/2866 [==============================] - 1s 219us/step - loss: 0.4778 - acc: 0.8018
Epoch 2/20
2866/2866 [==============================] - 1s 229us/step - loss: 0.4594 - acc: 0.8070
Epoch 3/20
2866/2866 [==============================] - 1s 238us/step - loss: 0.4415 - acc: 0.8081
Epoch 4/20
2866/2866 [==============================] - 1s 216us/step - loss: 0.4250 - acc: 0.8158
Epoch 5/20
2866/2866 [==============================] - 1s 215us/step - loss: 0.4263 - acc: 0.8133
Epoch 6/20
2866/2866 [==============================] - 1s 221us/step - loss: 0.4175 - acc: 0.8193
Epoch 7/20
2866/2866 [==============================] - 1s 229us/step - loss: 0.4137 - acc: 0.8262
Epoch 8/20
2866/2866 [==============================] - 1s 260us/step - loss: 0.3995 - acc: 0.8255
Epoch 9/20
2866/2866 [==============================] - 1s 235us/step - loss: 0.3963 - acc: 0.8329
Epoch 10/20
2866/2866 [==============================] - 1s 223us/step - loss: 0.3927 - acc: 0.8241
Epoch 11/

### Test LSTM Course DDD

In [68]:
y_pred_DDD = model.predict([DDD_Test_3D, DDD_AUX_Test])
y_classes_DDD = np.argmax(y_pred_DDD,axis=1)
y_classes_DDD

array([2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2,
       1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 0, 2, 1, 1, 2, 1, 2, 2, 2, 2,
       2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 1, 1, 2, 1, 2,
       2, 2, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2,
       2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1,
       1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 0, 1,
       2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 1,

In [69]:
print('Course DDD - 3 Target Classes')
print('Classification Report for LSTM predictions:')
print('-------------------------------------------')
print(classification_report(y_pred=y_classes_DDD, y_true=DDD_Test_Targets_1D))


Course DDD - 3 Target Classes
Classification Report for LSTM predictions:
-------------------------------------------
             precision    recall  f1-score   support

          0       0.80      0.11      0.19       112
          1       0.76      0.87      0.81       364
          2       0.80      0.85      0.82       680

avg / total       0.78      0.78      0.76      1156



# LSTM COURSE FFF

### Train LSTM Course FFF

In [29]:
model.fit([FFF_Train_3D,FFF_AUX_Train], FFF_Train_Targets_1HE, epochs=20, batch_size=32, verbose=1)

Epoch 1/20
3849/3849 [==============================] - 2s 466us/step - loss: 0.8398 - acc: 0.6654
Epoch 2/20
3849/3849 [==============================] - 1s 197us/step - loss: 0.6023 - acc: 0.7924
Epoch 3/20
3849/3849 [==============================] - 1s 199us/step - loss: 0.5523 - acc: 0.7968
Epoch 4/20
3849/3849 [==============================] - 1s 204us/step - loss: 0.5007 - acc: 0.8072
Epoch 5/20
3849/3849 [==============================] - 1s 222us/step - loss: 0.4758 - acc: 0.8062
Epoch 6/20
3849/3849 [==============================] - 1s 204us/step - loss: 0.4512 - acc: 0.8109
Epoch 7/20
3849/3849 [==============================] - 1s 205us/step - loss: 0.4299 - acc: 0.8132
Epoch 8/20
3849/3849 [==============================] - 1s 205us/step - loss: 0.4145 - acc: 0.8231
Epoch 9/20
3849/3849 [==============================] - 1s 201us/step - loss: 0.4158 - acc: 0.8187
Epoch 10/20
3849/3849 [==============================] - 1s 234us/step - loss: 0.4026 - acc: 0.8249
Epoch 11/

### Test LSTM Course FFF

In [30]:
y_pred_FFF = model.predict([FFF_Test_3D, FFF_AUX_Test])
y_classes_FFF = np.argmax(y_pred_FFF,axis=1)
y_classes_FFF

array([1, 1, 0, 1, 2, 1, 1, 2, 1, 2, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 0, 0, 1,
       1, 2, 0, 2, 2, 2, 2, 0, 2, 0, 0, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       1, 1, 2, 2, 1, 0, 0, 1, 2, 0, 2, 2, 2, 0, 2, 0, 0, 1, 2, 0, 1, 0, 2,
       0, 0, 2, 0, 2, 0, 1, 0, 1, 0, 1, 2, 1, 2, 2, 0, 0, 2, 0, 2, 2, 0, 2,
       1, 2, 2, 2, 2, 2, 2, 0, 2, 2, 0, 1, 2, 0, 1, 2, 1, 0, 2, 1, 0, 2, 1,
       0, 0, 2, 2, 0, 2, 0, 1, 2, 1, 2, 2, 2, 0, 1, 2, 0, 2, 2, 2, 2, 2, 0,
       0, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 0, 1,
       1, 0, 2, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 0, 2, 2, 2, 1, 0, 0, 0, 2, 0,
       0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 0, 2, 1, 2, 2, 2, 2, 2,
       2, 0, 0, 0, 2, 2, 0, 1, 2, 2, 1, 1, 0, 2, 1, 2, 0, 0, 0, 0, 2, 2, 1,
       2, 1, 2, 2, 2, 0, 0, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0,
       0, 2, 2, 2, 2, 1, 1, 2, 1, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1,
       2, 2, 2, 1, 0, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 0, 0, 2, 0, 2, 0, 0, 0,
       0, 2,

In [31]:
print('Course FFF - 3 Target Classes')
print('Classification Report for LSTM predictions:')
print('-------------------------------------------')
print(classification_report(y_pred=y_classes_FFF, y_true=FFF_Test_Targets_1D))


Course FFF - 3 Target Classes
Classification Report for LSTM predictions:
-------------------------------------------
             precision    recall  f1-score   support

          0       0.59      0.82      0.69       258
          1       0.93      0.83      0.88       393
          2       0.86      0.80      0.83       859

avg / total       0.83      0.81      0.82      1510



Epoch 1/20
3849/3849 [==============================] - 1s 370us/step - loss: 1.1211 - acc: 0.4838
Epoch 2/20
3849/3849 [==============================] - 0s 49us/step - loss: 1.0425 - acc: 0.5123
Epoch 3/20
3849/3849 [==============================] - 0s 63us/step - loss: 1.0263 - acc: 0.5110
Epoch 4/20
3849/3849 [==============================] - 0s 49us/step - loss: 1.0196 - acc: 0.5168
Epoch 5/20
3849/3849 [==============================] - 0s 48us/step - loss: 0.9916 - acc: 0.5386
Epoch 6/20
3849/3849 [==============================] - 0s 71us/step - loss: 1.0018 - acc: 0.5313
Epoch 7/20
3849/3849 [==============================] - 0s 50us/step - loss: 0.9949 - acc: 0.5404
Epoch 8/20
3849/3849 [==============================] - 0s 54us/step - loss: 0.9829 - acc: 0.5412
Epoch 9/20
3849/3849 [==============================] - 0s 53us/step - loss: 0.9683 - acc: 0.5459
Epoch 10/20
3849/3849 [==============================] - 0s 54us/step - loss: 0.9707 - acc: 0.5456
Epoch 11/20
3849/3